name: color_gen_app
version: 1.0.0+1
publish_to: none

description: Random color generation app.

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

  solid_lints: ^0.0.12

dependencies:
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0

  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  logger: ^1.1.0
  package_info_plus: ^3.0.2
  pausable_timer: ^1.0.0+6

flutter:
  uses-material-design: true
